language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - mkdir -p build/logs
  - composer install --dev
  - composer require --dev "satooshi/php-coveralls:dev-master"

script:
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - vendor
